#! /bin/bash


### pb with name of file with pgf90 32 bits



#
# NETCDF should be defined
#

pgf90 w2g.f -L$NETCDF/lib -lnetcdf -lm -I$NETCDF/include -Mfree -o w2g

#g95 w2g.f -L$NETCDF/lib -lnetcdf -lm -I$NETCDF/include -Wall -Wno=137,155 -fno-second-underscore -ffree-form -o w2g

#pgf90 -mcmodel=medium -Mlarge_arrays w2g.f -L$NETCDF/lib -lnetcdf -lm -I$NETCDF/include -Mfree -o w2g


#!=================================Make Executable============================
#!  Make executable:
#!    DEC Alpha
#!      f90 WRFnc2ctl.f -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -free  -o WRFnc2ctl
#!
#!   linux flags
#!      pgf90 WRFnc2ctl.f -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -Mfree  -o WRFnc2ctl
#!
#!   Sun flags
#!      f90 WRFnc2ctl.f -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -free  -o WRFnc2ctl
#!
#!   SGI flags 
#!      f90 WRFnc2ctl.f -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -freeform  -o WRFnc2ctl
#! 
#!   IBM flags
#!      xlf WRFnc2ctl.f -L/usr/local/lib32/r4i4 -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -qfree=f90  -o WRFnc2ctl
#! 
#!   Mac flags (with xlf compiler)
#!      xlf WRFnc2ctl.f -L/usr/local/netcdf-xlf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf-xlf/include  -qfree=f90  -o WRFnc2ctl



#!=================================Make Executable============================
#!  Make executable:
#!    DEC Alpha
#!      f90 p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -free  -o p_interp
#!
#!   Linux flags
#!      pgf90 p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -Mfree  -o p_interp
#!
#!   Sun flags
#!      f90 p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -free  -o p_interp
#!
#!   SGI flags
#!      f90 p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -freeform  -o p_interp
#!
#!   IBM flags 
#!      xlf p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -qfree=f90  -o p_interp
#!
#!   Mac flags (with xlf compiler)
#!      xlf p_interp.F90 -L/usr/local/netcdf-xlf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf-xlf/include  -qfree=f90  -o p_interp
#!
#!   Mac flags (with g95 compiler)
#!       g95 p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!       -I/usr/local/netcdf/include -ffree-form -o p_interp
#!
#!   Mac flags (with pgf90 compiler)
#!      pgf90 p_interp.F90 -L/usr/local/netcdf/lib -lnetcdf -lm  \
#!      -I/usr/local/netcdf/include  -Mfree  -o p_interp
#!
#!============================================================================

